replicaCount: 1
db:
  config:
    host: 'postgresql.postgresql.svc.cluster.local'
env:
  KAFKA_BROKERS: 'kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092'
  KAFKA_TOPIC: 'cve'
  KAFKA_CONSUMER_GROUP_ID: 'cve'
resources:
  limits:
    cpu: 500m
    memory: 384Mi
  requests:
    cpu: 250m
    memory: 256Mi
pod:
  readinessProbe:
    path: /readiness
    failureThreshold: 4
    successThreshold: 1
    periodSeconds: 15
  livenessProbe:
    path: /liveness
    failureThreshold: 3
    successThreshold: 1
    periodSeconds: 10
podLabels:
  fluentbit-logs: 'true'

pdb:
  create: true
  minAvailable: 2
  maxUnavailable: {}

autoscaling:
  hpa:
    enabled: true
    minReplicas: 3
    maxReplicas: 5
    targetCPU: 5
    targetMemory: 5
    annotations: {}
