prometheus:
  resourcesPreset: "small"
  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList:
        - job_name: 'stats'
          metrics_path: /metrics
          kubernetes_sd_configs:
            - role: service
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
              action: keep
              regex: true
operator:
  pdb:
    create: true
    minAvailable: 1
  resourcesPreset: "nano"

alertmanager:
  resourcesPreset: "nano"

blackboxExporter:
  resourcesPreset: "nano"
